# -*- coding: utf-8 -*-
"""buatBot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UEY_iAsT7KClsgyO7kBUD8TFwfB7-0GC
"""

!git config --list

!git config --global user.name "kunangBro"

!git clone https://github.com/kunangBro/buatBot.git

!git init

!git add buatBot2.py
!git commit -m "Menambahkan file baru"
!git remote add origin https://github.com/kunangBro/buatBot.git
!git branch -M main
!git push -u origin main





pip install python-telegram-bot==13.7

from telegram.ext import Updater, CommandHandler, CallbackContext
from telegram import Update
import random

# Variabel status untuk menunjukkan apakah bot sedang dalam mode chatting acak atau tidak
chatting_mode = False

# Fungsi yang akan dipanggil saat perintah /start diberikan ke bot
def start(update: Update, context: CallbackContext) -> None:
    global chatting_mode
    chatting_mode = False
    update.message.reply_text('Halo! Saya bot acak. Ketik /random untuk mulai berbicara dengan seseorang secara acak!')

# Fungsi untuk memproses perintah /random
def random_chat(update: Update, context: CallbackContext) -> None:
    global chatting_mode
    chatting_mode = True
    update.message.reply_text('Anda sedang mulai berbicara secara acak dengan seseorang. Ketik /stop untuk menghentikan percakapan.')

# Fungsi yang akan dipanggil saat perintah /stop diberikan ke bot
def stop_chat(update: Update, context: CallbackContext) -> None:
    global chatting_mode
    chatting_mode = False
    update.message.reply_text('Anda telah menghentikan percakapan dengan seseorang. Ketik /random untuk mulai berbicara lagi.')


def main() -> None:
    # Token bot yang diberikan oleh BotFather
    TOKEN = "6831867175:AAGelAzFApsFwGUQRs63vQVaFfQfDT1OdJc"

    # Buat instance Updater dengan parameter `use_context=True`
    updater = Updater(TOKEN)
    dispatcher = updater.dispatcher

    # Menambahkan handler untuk perintah /start, /random, /stop
    dispatcher.add_handler(CommandHandler("start", start))
    dispatcher.add_handler(CommandHandler("random", random_chat))
    dispatcher.add_handler(CommandHandler("stop", stop_chat))

    # Mulai bot
    updater.start_polling()
    updater.idle()

if __name__ == '__main__':
    main()